version: 2
jobs:
  build:
    working_directory: /srv/openchain/
    docker:
      - image: mantiby/openchain:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements-test.txt

      - run:
          name: Run flake8
          command: flake8

      - run:
          name: Create LevelDB data directory
          command: mkdir -p /var/lib/openchain/test/

      - run:
          name: Run unit tests with coverage
          command:
            export DATABASE_PATH='/var/lib/openchain/test/' &&
            coverage run -m unittest discover -s openchain/tests/ -p '*_tests.py' &&
            coverage report --fail-under=75 -m
