version: '3'
services:
  pool:
    image: mantiby/openchain:latest
    container_name: openchain-pool
    networks:
      docker-network:
        ipv4_address: 10.5.0.2
    environment:
      ROLE: pool
      IS_LOCAL: null
  logger:
    image: mantiby/openchain:latest
    container_name: openchain-logger
    networks:
      docker-network:
        ipv4_address: 10.5.0.3
    environment:
      ROLE: logger
      IS_LOCAL: null
  miner:
    image: mantiby/openchain:latest
    container_name: openchain-miner
    networks:
      docker-network:
        ipv4_address: 10.5.0.4
    environment:
      ROLE: miner
      IS_LOCAL: null
  wallet:
    image: mantiby/openchain:latest
    container_name: openchain-wallet
    networks:
      docker-network:
        ipv4_address: 10.5.0.5
    environment:
      ROLE: wallet
      IS_LOCAL: null
networks:
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16