version: '3'
services:
  pool:
    image: mantiby/openchain:latest
    container_name: openchain-pool
    networks:
      openchain:
        ipv4_address: 10.5.0.2
    environment:
      - ROLE=pool
  logger:
    image: mantiby/openchain:latest
    container_name: openchain-logger
    networks:
      openchain:
        ipv4_address: 10.5.0.3
    environment:
      - ROLE=logger
  miner:
    image: mantiby/openchain:latest
    container_name: openchain-miner
    networks:
      openchain:
        ipv4_address: 10.5.0.4
    environment:
      - ROLE=miner
  wallet:
    image: mantiby/openchain:latest
    container_name: openchain-wallet
    networks:
      openchain:
        ipv4_address: 10.5.0.5
    environment:
      - ROLE=wallet
networks:
  openchain:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16