version: '3'
services:
  openchain-pool:
    image: mantiby/openchain:latest
    container_name: openchain-pool
    environment:
      ROLE: pool
    volumes:
      - ./:/srv/openchain/
  openchain-miner:
    image: mantiby/openchain:latest
    container_name: openchain-miner
    links:
      - openchain-pool
    environment:
      ROLE: miner
    volumes:
      - ./:/srv/openchain/
    ports:
      - "8000:8000"
  openchain-wallet-01:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-01
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/
  openchain-wallet-02:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-02
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/
  openchain-wallet-03:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-03
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/