version: '3'
services:
  openchain-pool:
    image: mantiby/openchain:latest
    container_name: openchain-pool
    environment:
      ROLE: pool
    volumes:
      - ./app:/srv/openchain/
  openchain-generator:
    image: mantiby/openchain:latest
    container_name: openchain-generator
    links:
      - openchain-pool
    environment:
      ROLE: generator
    volumes:
      - ./app:/srv/openchain/
  openchain-builder:
    image: mantiby/openchain:latest
    container_name: openchain-builder
    environment:
      ROLE: builder
    ports:
      - "8000:8000"
    volumes:
      - ./app:/srv/openchain/
  openchain-wallet-01:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-01
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./app:/srv/openchain/
  openchain-wallet-02:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-02
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./app:/srv/openchain/
  openchain-wallet-03:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-03
    links:
      - openchain-pool
      - openchain-miner
    environment:
      ROLE: wallet
    volumes:
      - ./app:/srv/openchain/