version: '3'
services:
  pool:
    image: mantiby/openchain:latest
    container_name: openchain-pool
    networks:
      docker-network:
        ipv4_address: 10.5.0.2
    environment:
      ROLE: pool
    volumes:
      - ./:/srv/openchain/
  miner:
    image: mantiby/openchain:latest
    container_name: openchain-miner
    networks:
      docker-network:
        ipv4_address: 10.5.0.4
    environment:
      ROLE: miner
    volumes:
      - ./:/srv/openchain/
    ports:
      - "8000:8000"
  wallet-01:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-01
    networks:
      docker-network:
        ipv4_address: 10.5.0.5
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/
  wallet-02:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-02
    networks:
      docker-network:
        ipv4_address: 10.5.0.6
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/
  wallet-03:
    image: mantiby/openchain:latest
    container_name: openchain-wallet-03
    networks:
      docker-network:
        ipv4_address: 10.5.0.7
    environment:
      ROLE: wallet
    volumes:
      - ./:/srv/openchain/
networks:
  docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16